services:
  couchdb:
    image: couchdb:latest
    container_name: Obsidian-CouchDB
    user: 1000:1000
    environment:
      SERVER_URL: ${SERVER_URL}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DATABASE: ${COUCHDB_DATABASE}
    volumes:
      - /srv/apps/couchdb/data:/opt/couchdb/data
      - /srv/apps/couchdb/etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.entrypoints=websecure"
      - "traefik.http.routers.couchdb.rule=Host(`obsidian.burgoyne.casa`)"
      - "traefik.http.routers.couchdb.tls=true"
      - "traefik.http.routers.couchdb.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true